apiVersion: v1
kind: ConfigMap
metadata:
  name: order-configmap
  namespace: slanza
data:
  database_url: order-postgres-service:5432
  database_name: orderdb
  spring_app_port: "8080"
  pgadmin_listen_port: "5050"
  pgadmin_baseurl: /api/v1/order/pgadmin