apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-postgres-statefulset
  namespace: slanza
  labels:
    app: order-postgres
spec:
  serviceName: order-postgres
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: order-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: database_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: postgres-root-password
          volumeMounts:
            - name: order-postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: order-postgres-persistent-storage
      spec:
        storageClassName: cdk-cinder
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-postgres-service
  namespace: slanza
spec:
  selector:
    app: order-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
