apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-spring-app-deployment
  namespace: slanza
  labels:
    app: order-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-spring-app
  template:
    metadata:
      labels:
        app: order-spring-app
    spec:
      containers:
        - name: order-spring-app
          image: silviolanza/order-spring-app
          ports:
            - containerPort: 8080
          #imagePullPolicy: Never
          env:
            - name: GSF_DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: database_url
            - name: GSF_POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: database_name
            - name: GSF_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: postgres-root-username
            - name: GSF_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: postgres-root-password
            - name: GSF_WEB_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: spring_app_port
---
apiVersion: v1
kind: Service
metadata:
  name: order-spring-app-service
  namespace: slanza
spec:
  selector:
    app: order-spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
