version: '3.2'
services:
  order-postgres:
    container_name: order-postgres
    image: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - order-network
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  order-pgadmin:
    container_name: order-pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
      SCRIPT_NAME: /api/v1/customers/pgadmin
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - order-postgres
    networks:
      - order-network
  order-spring-app:
    build: .
    image:  order-spring-app
    restart: unless-stopped
    container_name:  order-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - order-postgres
    networks:
      - order-network
    environment:
      - GSF_DB_SERVER=order-postgres:5432
      - GSF_POSTGRES_DB=customerdb
      - GSF_POSTGRES_USER=admin
      - GSF_POSTGRES_PASSWORD=admin
      - GSF_WEB_SERVER_PORT=8080
volumes:
  db-data:
  pgadmin-data:
networks:
  order-network:
    driver: bridge