apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-configmap
  namespace: slanza
data:
  database_url: customer-postgres-service:5432
  database_name: customerdb
  spring_app_port: "8080"
  pgadmin_listen_port: "5050"
  pgadmin_baseurl: /api/v1/customers/pgadmin