apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongodb-namespace
data:
  database_url: mongodb-service
  database_port: "27017"
  database_db_auth: admin
  database_name: stores
  spring_app_port: "8080"