version: '3.2'
services:

  store-mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ~/.docker-conf/mongodb/data/:/data/db
    networks:
      - store-net

  store-mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: store-mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #ME_CONFIG_SITE_BASEURL: /express
    networks:
      - store-net
    depends_on:
      - store-mongo

  store-spring-app:
    build: ./
    restart: unless-stopped
    container_name: store-spring-app
    environment:
      GSF_MONGO_DB_HOST: store-mongo
      GSF_MONGO_DB_PORT: "27017"
      GSF_MONGO_DB_AUTH: admin
      GSF_MONGO_DB_USER: root
      GSF_MONGO_DB_PASS: example
      GSF_MONGO_DB_NAME: stores
      STORE_WEB_SERVER_PORT: "8080"
    ports:
      - 8080:8080
    networks:
      - store-net
    depends_on:
      - store-mongo

networks:
  store-net:
    driver: bridge