apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mongodb-deployment
  namespace: slanza
  labels:
    app: product-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mongodb
  template:
    metadata:
      labels:
        app: product-mongodb
    spec:
      containers:
        - name: product-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: product-mongodb-service
  namespace: slanza
spec:
  selector:
    app: product-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
