apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-mongodb-express-deployment
  namespace: slanza
  labels:
    app: store-mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-mongodb-express
  template:
    metadata:
      labels:
        app: store-mongodb-express
    spec:
      containers:
        - name: store-mongodb-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: store-configmap
                  key: database_url
            - name: ME_CONFIG_SITE_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: store-configmap
                  key: mongo_express_baseurl
---
apiVersion: v1
kind: Service
metadata:
  name: store-mongodb-express-service
  namespace: slanza
spec:
  selector:
    app: store-mongodb-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
