name: Docker Image CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image of Customer Service
    - run:  docker build --no-cache -t silviolanza/customer-spring-app:$(date +%s) ./customer-service
      
