version: '3.2'
services:

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ~/.docker-conf/mongodb/data/:/data/db
    networks:
      - mongonet

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mongonet
    depends_on:
      - mongo

  spring-app:
    build: ./springboot-mongodb-file-upload-download
    restart: unless-stopped
    container_name: spring-app
    environment:
      MONGO_DB_PORT: "27017"
      MONGO_DB_HOST: mongo
      MONGO_DB_NAME: user
      MONGO_DB_USER: root
      MONGO_DB_PASS: example
    ports:
      - 8080:8080
    networks:
      - mongonet
    depends_on:
      - mongo

networks:
  mongonet:
    driver: bridge